In [1]:
import pandas as pd
import numpy as np

In [2]:
coffee_sales = pd.read_csv("C:\\Users\\Oluwanifemi\\Documents\\Coffee Sales.csv")

In [3]:
coffee_sales.head()

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte

In [4]:
coffee_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3636 entries, 0 to 3635
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3636 non-null   object
 1   datetime     3636 non-null   object
 2   cash_type    3636 non-null   object
 3   card         3547 non-null   object
 4   money        3636 non-null   float64
 5   coffee_name  3636 non-null   object
dtypes: float64(1), object(5)
memory usage: 170.6+ KB

In [5]:
coffee_sales.describe()

             money
count  3636.000000
mean     31.746859
std       4.919926
min      18.120000
25%      27.920000
50%      32.820000
75%      35.760000
max      40.000000

In [6]:
coffee_sales.duplicated().sum()

np.int64(0)

In [7]:
coffee_sales.isnull().sum()

date            0
datetime        0
cash_type       0
card           89
money           0
coffee_name     0
dtype: int64

In [8]:
coffee_sales.rename(columns={"cash_type":"payment_method"}, inplace=True)

In [9]:
coffee_sales.rename(columns={"card":"card_no."}, inplace=True)

In [10]:
coffee_sales.rename(columns={"money":"amount"}, inplace=True)

In [11]:
coffee_sales["card_no."].fillna("Cash", inplace=True)

C:\Users\Oluwanifemi\AppData\Local\Temp\ipykernel_11828\898008051.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  coffee_sales["card_no."].fillna("Cash", inplace=True)

In [12]:
coffee_sales.isnull().sum()

date              0
datetime          0
payment_method    0
card_no.          0
amount            0
coffee_name       0
dtype: int64

In [13]:
coffee_sales.head(20)

,date,datetime,payment_method,card_no.,amount,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte
5,2024-03-01,2024-03-01 15:39:47.726,card,ANON-0000-0000-0005,33.8,Americano with Milk
6,2024-03-01,2024-03-01 16:19:02.756,card,ANON-0000-0000-0006,38.7,Hot Chocolate
7,2024-03-01,2024-03-01 18:39:03.580,card,ANON-0000-0000-0007,33.8,Americano with Milk
8,2024-03-01,2024-03-01 19:22:01.762,card,ANON-0000-0000-0008,38.7,Cocoa
9,2024-03-01,2024-03-01 19:23:15.887,card,ANON-0000-0000-0008,33.8,Americano with Milk
10,2024-03-01,2024-03-01 19:29:17.391,card,ANON-0000-0000-0009,33.8,Americano with Milk
11,2024-03-02,2024-03-02 10:22:06.957,card,ANON-0000-0000-0010,28.9,Americano
12,2024-03-02,2024-03-02 10:30:35.668,cash,Cash,40.0,Latte
13,2024-03-02,2024-03-02 10:41:41.249,card,ANON-0000-0000-0011,33.8,Americano with Milk
14,2024-03-02,2024-03-02 11:59:45.484,card,ANON-0000-0000-0012,33.8,Americano with Milk
15,2024-03-02,2024-03-02 14:38:35.535,card,ANON-0000-0000-0013,28.9,Americano
16,2024-03-02,2024-03-02 16:37:24.475,card,ANON-0000-0000-0014,33.8,Americano with Milk
17,2024-03-02,2024-03-02 17:34:54.969,card,ANON-0000-0000-0004,28.9,Americano
18,2024-03-03,2024-03-03 10:10:43.981,cash,Cash,40.0,Latte
19,2024-03-03,2024-03-03 10:27:18.561,card,ANON-0000-0000-0015,38.7,Latte

In [14]:
coffee_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3636 entries, 0 to 3635
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            3636 non-null   object
 1   datetime        3636 non-null   object
 2   payment_method  3636 non-null   object
 3   card_no.        3636 non-null   object
 4   amount          3636 non-null   float64
 5   coffee_name     3636 non-null   object
dtypes: float64(1), object(5)
memory usage: 170.6+ KB

In [15]:
coffee_sales["date"] = pd.to_datetime(coffee_sales["date"])

In [16]:
coffee_sales["datetime"] = pd.to_datetime(coffee_sales["datetime"])

In [17]:
coffee_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3636 entries, 0 to 3635
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            3636 non-null   datetime64[ns]
 1   datetime        3636 non-null   datetime64[ns]
 2   payment_method  3636 non-null   object
 3   card_no.        3636 non-null   object
 4   amount          3636 non-null   float64
 5   coffee_name     3636 non-null   object
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 170.6+ KB

In [18]:
coffee_sales["coffee_name"].unique()

array(['Latte', 'Hot Chocolate', 'Americano', 'Americano with Milk',
       'Cocoa', 'Cortado', 'Espresso', 'Cappuccino'], dtype=object)

In [19]:
coffee_sales["payment_method"].unique()

array(['card', 'cash'], dtype=object)

In [20]:
coffee_sales["coffee_name"] = coffee_sales["coffee_name"].astype("category")

In [21]:
coffee_sales["payment_method"] = coffee_sales["payment_method"].astype("category")

In [22]:
coffee_sales["hour"]=coffee_sales["datetime"].dt.hour

In [23]:
coffee_sales["day"]=coffee_sales["datetime"].dt.day_name()

In [24]:
def time_of_day(hour):
    if hour < 12:
        return "Morning"
    elif hour < 17:
        return "Afternoon"
    else:
        return "Evening"

In [25]:
coffee_sales["time_of_day"] = coffee_sales["hour"].apply(time_of_day)

In [26]:
coffee_sales.head(20)

,date,datetime,payment_method,card_no.,amount,coffee_name,hour,day,time_of_day
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte,10,Friday,Morning
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate,12,Friday,Afternoon
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate,12,Friday,Afternoon
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano,13,Friday,Afternoon
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte,13,Friday,Afternoon
5,2024-03-01,2024-03-01 15:39:47.726,card,ANON-0000-0000-0005,33.8,Americano with Milk,15,Friday,Afternoon
6,2024-03-01,2024-03-01 16:19:02.756,card,ANON-0000-0000-0006,38.7,Hot Chocolate,16,Friday,Afternoon
7,2024-03-01,2024-03-01 18:39:03.580,card,ANON-0000-0000-0007,33.8,Americano with Milk,18,Friday,Evening
8,2024-03-01,2024-03-01 19:22:01.762,card,ANON-0000-0000-0008,38.7,Cocoa,19,Friday,Evening
9,2024-03-01,2024-03-01 19:23:15.887,card,ANON-0000-0000-0008,33.8,Americano with Milk,19,Friday,Evening
10,2024-03-01,2024-03-01 19:29:17.391,card,ANON-0000-0000-0009,33.8,Americano with Milk,19,Friday,Evening
11,2024-03-02,2024-03-02 10:22:06.957,card,ANON-0000-0000-0010,28.9,Americano,10,Saturday,Morning
12,2024-03-02,2024-03-02 10:30:35.668,cash,Cash,40.0,Latte,10,Saturday,Morning
13,2024-03-02,2024-03-02 10:41:41.249,card,ANON-0000-0000-0011,33.8,Americano with Milk,10,Saturday,Morning
14,2024-03-02,2024-03-02 11:59:45.484,card,ANON-0000-0000-0012,33.8,Americano with Milk,11,Saturday,Morning
15,2024-03-02,2024-03-02 14:38:35.535,card,ANON-0000-0000-0013,28.9,Americano,14,Saturday,Afternoon
16,2024-03-02,2024-03-02 16:37:24.475,card,ANON-0000-0000-0014,33.8,Americano with Milk,16,Saturday,Afternoon
17,2024-03-02,2024-03-02 17:34:54.969,card,ANON-0000-0000-0004,28.9,Americano,17,Saturday,Evening
18,2024-03-03,2024-03-03 10:10:43.981,cash,Cash,40.0,Latte,10,Sunday,Morning
19,2024-03-03,2024-03-03 10:27:18.561,card,ANON-0000-0000-0015,38.7,Latte,10,Sunday,Morning

In [27]:
coffee_sales['amount'].describe()

count    3636.000000
mean       31.746859
std         4.919926
min        18.120000
25%        27.920000
50%        32.820000
75%        35.760000
max        40.000000
Name: amount, dtype: float64

In [28]:
coffee_sales['time']=coffee_sales['datetime'].dt.time

In [29]:
coffee_sales=coffee_sales[['date', 'time', 'datetime', 'day', 'time_of_day', 'hour', 'payment_method', 'card_no.', 'amount', 'coffee_name']]

In [30]:
coffee_sales.head(30)

,date,time,datetime,day,time_of_day,hour,payment_method,card_no.,amount,coffee_name
0,2024-03-01,10:15:50.520000,2024-03-01 10:15:50.520,Friday,Morning,10,card,ANON-0000-0000-0001,38.7,Latte
1,2024-03-01,12:19:22.539000,2024-03-01 12:19:22.539,Friday,Afternoon,12,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01,12:20:18.089000,2024-03-01 12:20:18.089,Friday,Afternoon,12,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01,13:46:33.006000,2024-03-01 13:46:33.006,Friday,Afternoon,13,card,ANON-0000-0000-0003,28.9,Americano
4,2024-03-01,13:48:14.626000,2024-03-01 13:48:14.626,Friday,Afternoon,13,card,ANON-0000-0000-0004,38.7,Latte
5,2024-03-01,15:39:47.726000,2024-03-01 15:39:47.726,Friday,Afternoon,15,card,ANON-0000-0000-0005,33.8,Americano with Milk
6,2024-03-01,16:19:02.756000,2024-03-01 16:19:02.756,Friday,Afternoon,16,card,ANON-0000-0000-0006,38.7,Hot Chocolate
7,2024-03-01,18:39:03.580000,2024-03-01 18:39:03.580,Friday,Evening,18,card,ANON-0000-0000-0007,33.8,Americano with Milk
8,2024-03-01,19:22:01.762000,2024-03-01 19:22:01.762,Friday,Evening,19,card,ANON-0000-0000-0008,38.7,Cocoa
9,2024-03-01,19:23:15.887000,2024-03-01 19:23:15.887,Friday,Evening,19,card,ANON-0000-0000-0008,33.8,Americano with Milk
10,2024-03-01,19:29:17.391000,2024-03-01 19:29:17.391,Friday,Evening,19,card,ANON-0000-0000-0009,33.8,Americano with Milk
11,2024-03-02,10:22:06.957000,2024-03-02 10:22:06.957,Saturday,Morning,10,card,ANON-0000-0000-0010,28.9,Americano
12,2024-03-02,10:30:35.668000,2024-03-02 10:30:35.668,Saturday,Morning,10,cash,Cash,40.0,Latte
13,2024-03-02,10:41:41.249000,2024-03-02 10:41:41.249,Saturday,Morning,10,card,ANON-0000-0000-0011,33.8,Americano with Milk
14,2024-03-02,11:59:45.484000,2024-03-02 11:59:45.484,Saturday,Morning,11,card,ANON-0000-0000-0012,33.8,Americano with Milk
15,2024-03-02,14:38:35.535000,2024-03-02 14:38:35.535,Saturday,Afternoon,14,card,ANON-0000-0000-0013,28.9,Americano
16,2024-03-02,16:37:24.475000,2024-03-02 16:37:24.475,Saturday,Afternoon,16,card,ANON-0000-0000-0014,33.8,Americano with Milk
17,2024-03-02,17:34:54.969000,2024-03-02 17:34:54.969,Saturday,Evening,17,card,ANON-0000-0000-0004,28.9,Americano
18,2024-03-03,10:10:43.981000,2024-03-03 10:10:43.981,Sunday,Morning,10,cash,Cash,40.0,Latte
19,2024-03-03,10:27:18.561000,2024-03-03 10:27:18.561,Sunday,Morning,10,card,ANON-0000-0000-0015,38.7,Latte
20,2024-03-03,11:33:56.118000,2024-03-03 11:33:56.118,Sunday,Morning,11,card,ANON-0000-0000-0016,28.9,Cortado
21,2024-03-03,12:26:56.098000,2024-03-03 12:26:56.098,Sunday,Afternoon,12,card,ANON-0000-0000-0012,28.9,Americano
22,2024-03-03,13:09:36.321000,2024-03-03 13:09:36.321,Sunday,Afternoon,13,card,ANON-0000-0000-0017,38.7,Hot Chocolate
23,2024-03-03,17:06:40.271000,2024-03-03 17:06:40.271,Sunday,Evening,17,card,ANON-0000-0000-0018,38.7,Cocoa
24,2024-03-03,17:08:45.895000,2024-03-03 17:08:45.895,Sunday,Evening,17,card,ANON-0000-0000-0019,28.9,Cortado
25,2024-03-03,18:03:23.369000,2024-03-03 18:03:23.369,Sunday,Evening,18,card,ANON-0000-0000-0020,33.8,Americano with Milk
26,2024-03-03,18:04:27.946000,2024-03-03 18:04:27.946,Sunday,Evening,18,card,ANON-0000-0000-0020,33.8,Americano with Milk
27,2024-03-03,18:08:04.959000,2024-03-03 18:08:04.959,Sunday,Evening,18,card,ANON-0000-0000-0020,38.7,Hot Chocolate
28,2024-03-04,10:03:51.994000,2024-03-04 10:03:51.994,Monday,Morning,10,card,ANON-0000-0000-0001,38.7,Latte
29,2024-03-04,10:54:50.958000,2024-03-04 10:54:50.958,Monday,Morning,10,card,ANON-0000-0000-0021,38.7,Latte